import { Space_Mono } from "next/font/google";
import "./globals.css";
import Footer from "@/components/shared/Footer";
import { Suspense } from "react";
import Loading from "./loading";

const spaceMono = Space_Mono({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata = {
  title: "GyaanSaar AI",
  description:
    "Crafted with GyaanSaar AI — an open-source article summarizer that condenses long reads into sharp summaries using the intelligence of GPT-4.",
  other: {
    "twitter:image": "https://vf33u6a4xs.ufs.sh/f/knEGXHgaJ8qP4rsiutcQvFsDK3aLmd8jtokNYeZ26RXJUf05",
    "twitter:card": "summary_image_large",
    "twitter:url": "https://gyaansaar-ai.vercel.app/",
    "twitter:domain": "gyaansaar-ai.vercel.app",
    "twitter:title": "GyaanSaar AI",
    "twitter:description":
      "Crafted with GyaanSaar AI — an open-source article summarizer that condenses long reads into sharp summaries using the intelligence of GPT-4.",

    "og:url": "https://gyaansaar-ai.vercel.app/",
    "og:type": "website",
    "og:title": "GyaanSaar AI",
    "og:description":
      "Generated by create next appEnhance your reading with Kshitij, an open-source article summarizer that transforms lengthy articles into concise summaries using the powerful GPT-4.",
    "og:image": "https://vf33u6a4xs.ufs.sh/f/knEGXHgaJ8qP4rsiutcQvFsDK3aLmd8jtokNYeZ26RXJUf05",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${spaceMono.className} bg-background justify-evenly min-h-screen flex flex-col`}
      >
        <Suspense fallback={<Loading />}>
          {children}
          <Footer />
        </Suspense>
      </body>
    </html>
  );
}
